#ifndef EXIT_CODES_CYPHER_H
#define EXIT_CODES_CYPHER_H

typedef enum
{
    EXIT_OK,
    EXIT_MALLOC_FAIL,
    EXIT_UNKNOWN_INSTRUCTION,
    EXIT_NO_OPTION_VALUE,
    EXIT_INVALID_INSTRUCTION_SET
} exit_code_t;

#endif // EXIT_CODES_CYPHER_H